### ISSUE TITLE
Add more info in README.md

### ISSUE THREAD

**Issue by Clyybber** [Chemrat/redshift-qt#5]
Currently i myself am confused at what this provides over redshift-gtk and if it has an equivalent feature set. I think it would be better to add more info.

**Comment by Chemrat** [comment]
It doesn't really provide anything over redshift-gtk apart from not depending on gtk/appindicator, it's just a more KDE-friendly version of redshift-gtk
I don't have any plans to add any more features because I'm content with the current basic set, but you're free to open a feature request issue or pull request
